### ISSUE TITLE
How to extract waypoints from gpu

### ISSUE THREAD

**Issue by duncangroenewald** [mmllr/GPXKit#10]
Its not clear whether this library can extract waypoints from a gpu file or whether it is only capable of reading a track recorded in a gpu file format.

Can you update the documentation to indicate whether the library can extract waypoints and routes from a gpu file and include examples use cases for doing so.  

Thanks

**Comment by mmllr** [comment]
Can you please provide a PR to explain what you mean?

**Comment by duncangroenewald** [comment]
I just wanted to read the list of waypoints from the gpx file.  The file can have waypoints, tracks and routes.

Anyway I found GPX which is a Swift struct and in conjunction with XMLEncoder it will allow read and write of gpx files so that seemed simpler to use.  Thanks anyway.
